import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";
import ThemeSwitch from "@/components/theme-switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dragoș-Ionuț Talabă | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={'${inter.className} bg-slate-200 text-slate-950 relative h-auto pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity'}>
        <div className="bg-[#ffe9c7] -z-10 absolute top-[-6rem] right-[5rem] h-[40rem] w-[40rem] rounded-full blur-[10rem] sm:w-[65rem]"></div>
        <div className="bg-[#e9ffc7] -z-10 absolute top-[-6rem] left-[-5rem] h-[40rem] w-[40rem] rounded-full blur-[10rem] sm:w-[65rem]"></div>
        <ActiveSectionContextProvider>
          <Header />
          {children}
          <Footer/>
        </ActiveSectionContextProvider>
        <ThemeSwitch/>
        </body>
    </html>
  );
}
